# Generated by Django 4.0.5 on 2022-06-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('repeat', models.BooleanField(default=0, max_length=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
